import { PageSchema } from "@/components/constructor/page-render/types";
import {
    COMPANY_NAME,
    COMPANY_LEGAL_NAME,
    COMPANY_NUMBER,
    COMPANY_ADDRESS,
    COMPANY_EMAIL,
} from "@/resources/constants";

const termsSchema: PageSchema = {
    meta: {
        title: `Terms & Conditions – ${COMPANY_NAME}`,
        description: `Terms and Conditions for ${COMPANY_NAME}: eligibility, credits, payments, refunds, health disclaimers, IP, liability, and governing law.`,
        keywords: [
            "terms",
            "terms and conditions",
            "service terms",
            "refund policy",
            "liability",
            "fitness plans",
            "workout generator",
        ],
        canonical: "/terms",
        ogImage: {
            title: `${COMPANY_NAME} – Terms & Conditions`,
            description: "Transparent and legally compliant terms for service usage.",
            bg: "#ffffff",
            color: "#000000",
        },
    },

    blocks: [
        {
            type: "text",
            title: "Terms and Conditions",
            bullets: [
                "Effective date: 15 September 2025",
                `These Terms govern access to and use of ${COMPANY_NAME} operated by ${COMPANY_LEGAL_NAME}.`,
            ],
        },

        {
            type: "text",
            title: "1. Introduction",
            bullets: [
                `1.1. These Terms apply to your use of the ${COMPANY_NAME} website and services operated by ${COMPANY_LEGAL_NAME} (Company No. ${COMPANY_NUMBER}, registered office: ${COMPANY_ADDRESS}).`,
                "1.2. By creating an account, purchasing Credits, booking paid services, or using the platform, you agree to be bound by these Terms.",
                "1.3. If you do not agree with these Terms, you must not use the Service.",
            ],
        },

        {
            type: "text",
            title: "2. Definitions",
            bullets: [
                "2.1. Account – the user account created on the Service.",
                "2.2. Training Plan(s) – personalised or template-based workout programmes, exercise routines, nutrition or fitness guidance delivered digitally.",
                "2.3. Credits (Tokens) – internal virtual credits used to access Services.",
                "2.4. Services / Products – Training Plans, consultations, coaching, AI-generated fitness content, and related offerings.",
                "2.5. You / Customer – any individual or legal entity using the Service.",
            ],
        },

        {
            type: "text",
            title: "3. Eligibility and Account Registration",
            bullets: [
                "3.1. You must be at least 18 years old to register and use the Service.",
                "3.2. If acting on behalf of a company, you confirm you are authorised to do so.",
                "3.3. You must provide accurate, current and complete information and keep it updated.",
                `3.4. Any unauthorised access to your Account must be reported immediately to ${COMPANY_EMAIL}.`,
            ],
        },

        {
            type: "text",
            title: "4. Credits (Tokens)",
            bullets: [
                "4.1. Credits are a virtual internal accounting unit and are not legal tender, currency or investments.",
                "4.2. The nominal value of Credits is displayed at checkout.",
                "4.3. We may update Credit pricing prospectively.",
                "4.4. Services may be priced in Credits.",
                "4.5. Credits are credited after successful payment and deducted upon redemption.",
                "4.6. Promotional or bonus Credits may be offered subject to specific conditions.",
            ],
        },

        {
            type: "text",
            title: "5. Ordering, Payment and Checkout",
            bullets: [
                "5.1. Orders placed through the Service are subject to acceptance.",
                "5.2. Available payment methods are shown at checkout.",
                "5.3. At checkout you will see the Credits used, nominal value, fiat price and applicable taxes or fees.",
                "5.4. Access to digital Services is granted after payment confirmation.",
            ],
        },

        {
            type: "text",
            title: "6. Delivery of Digital Content",
            bullets: [
                "6.1. All Services are delivered digitally. No physical goods are shipped.",
                "6.2. Delivery occurs when Training Plans or related digital content become available in your Account, via download or online access.",
                "6.3. Content may be generated by artificial intelligence, human trainers, or a combination of both.",
                "6.4. Re-accessing or re-downloading the same Training Plan does not consume additional Credits.",
                "6.5. If delivery fails due to a technical issue attributable to us, we may re-deliver the content or restore Credits.",
                `6.6. Support requests must be submitted to ${COMPANY_EMAIL} with relevant order details.`,
            ],
        },

        {
            type: "text",
            title: "7. Refunds, Cancellations and Consumer Rights",
            bullets: [
                "7.1. Where digital content is supplied immediately with your consent, statutory cancellation rights may be lost.",
                "7.2. Unused Credits may be refundable prior to use, subject to fees.",
                "7.3. If a Training Plan or Service is faulty or not as described, contact support with full details.",
                "7.4. Refund or cancellation requests are reviewed on a case-by-case basis.",
            ],
        },

        {
            type: "text",
            title: "8. Health & Safety; No Medical Advice",
            bullets: [
                "8.1. Training Plans are provided for informational and fitness purposes only.",
                "8.2. The Service does not provide medical advice.",
                "8.3. Consult a qualified healthcare professional before starting any exercise programme.",
                "8.4. You confirm you are physically able to perform the recommended activities.",
                "8.5. The Company is not responsible for injuries, health issues or damages arising from use of the Service.",
            ],
        },

        {
            type: "text",
            title: "9. Intellectual Property Rights",
            bullets: [
                `9.1. All intellectual property rights in the Service and content belong to ${COMPANY_LEGAL_NAME} unless stated otherwise.`,
                "9.2. You receive a limited, non-transferable licence for personal, non-commercial use.",
                "9.3. You may not copy, reproduce, distribute or resell Training Plans without permission.",
            ],
        },

        {
            type: "text",
            title: "10. Warranties and Disclaimers",
            bullets: [
                "10.1. We warrant that we have the right to provide the Services.",
                "10.2. Services are provided “as is” and “as available”.",
                "10.3. Individual fitness results may vary and are not guaranteed.",
            ],
        },

        {
            type: "text",
            title: "11. Limitation of Liability",
            bullets: [
                "11.1. Nothing limits liability for death or personal injury caused by negligence or fraud.",
                "11.2. Total liability is capped at the amount paid by you in the preceding 12 months.",
                "11.3. We are not liable for indirect or consequential losses, including loss of data or profits.",
            ],
        },

        {
            type: "text",
            title: "12. Indemnity",
            bullets: [
                "12.1. Your breach of these Terms.",
                "12.2. Your misuse of the Service or Training Plans.",
                "12.3. Your violation of applicable laws or third-party rights.",
            ],
        },

        {
            type: "text",
            title: "13. Data Protection",
            bullets: [
                `13.1. ${COMPANY_NAME} processes personal data in accordance with UK GDPR and the Data Protection Act 2018.`,
                "13.2. Further details are set out in our Privacy Policy.",
            ],
        },

        {
            type: "text",
            title: "14. Third Party Links and Content",
            bullets: [
                "14.1. The Service may link to third-party websites or tools.",
                "14.2. We are not responsible for third-party content or privacy practices.",
            ],
        },

        {
            type: "text",
            title: "15. Suspension and Termination",
            bullets: [
                "15.1. We may suspend or terminate Accounts for breach, fraud or security reasons.",
                "15.2. Upon termination, access to Training Plans may cease.",
                "15.3. Termination does not affect accrued rights.",
            ],
        },

        {
            type: "text",
            title: "16. Changes to These Terms",
            bullets: [
                `16.1. ${COMPANY_NAME} may update these Terms from time to time.`,
                "16.2. Continued use of the Service constitutes acceptance of updated Terms.",
            ],
        },

        {
            type: "text",
            title: "17. Notices",
            bullets: [
                `17.1. Notices to the Company must be sent to ${COMPANY_EMAIL} or the registered office.`,
                "17.2. Notices to you may be sent by email or via the Service.",
            ],
        },

        {
            type: "text",
            title: "18. Governing Law and Jurisdiction",
            bullets: [
                "18.1. These Terms are governed by the laws of England and Wales.",
                "18.2. Courts of England and Wales have jurisdiction, subject to consumer protection laws.",
            ],
        },

        {
            type: "text",
            title: "19. Miscellaneous",
            bullets: [
                "19.1. If any provision is invalid, remaining provisions continue in force.",
                "19.2. Failure to enforce a right is not a waiver of that right.",
            ],
        },

        {
            type: "text",
            title: "20. Contact Details",
            bullets: [
                `Company: ${COMPANY_LEGAL_NAME}`,
                `Company number: ${COMPANY_NUMBER}`,
                `Address: ${COMPANY_ADDRESS}`,
                `Email: ${COMPANY_EMAIL}`,
            ],
        },
    ],
};

export default termsSchema;
